platform :ios, '7.0'
pod 'XMPPFramework', '~> 3.6.6'
pod 'AFNetworking', '~> 3.0.4'
pod 'FMDB', '~> 2.6'
pod 'RegexKitLite', '~> 4.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension', '~> 3.0.10'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Reachability', '~> 3.2'
pod 'TREmotion', '~> 0.0.2'
